name: Daily run [Node16-westus2] - lwa-sample-node-16-westus2
on: 
    schedule:
      - cron: '20 8 * * *' # every day at 8:20 UTC

env:
  AZURE_WEBAPP_NAME: lwa-sample-node-16-westus2   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './mySampleApp'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
      with:
        ref: 'node-16'
   
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS_E2E_SERVICE_PRINCIPAL }}
        
    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory: ./mySampleApp
               
    # deploy web app using Azure credentials
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    # Azure logout 
    - name: logout
      run: |
        az logout
